### ISSUE TITLE
Verify address via PORTAL displays a wrong address

### ISSUE THREAD

**Issue by alexandre-k** [TwentyTwoHW/portal-software#28]
Hello,

When one uses the Portal to "verify address via PORTAL" on Nunchuk, the Portal displays a wrong address as it doesn't match the address on Nunchuk.

To reproduce this error, create a multisig wallet, like 3/4 and then try to receive bitcoins on an address. Then on the three dots button in Nunchuk, check verify address via PORTAL, press the button on the Portal and see it is wrong.

**Comment by afilini** [comment]
Thanks for reporting this, I'll try to reproduce the issue locally

**Comment by afilini** [comment]
Did you register the multisig on Portal after setting it up in Nunchuk? Unfortunately that step is not very clear unless you know where to look for it, we are working on tutorial videos to release to help people set it up.

**Comment by alexandre-k** [comment]
Thank you for your reply.
I see. I didn't register the multisig on Portal, just added it as a key. So indeed I may be missing this step. I will be waiting for the tutorial video, unless there is a documentation elsewhere.

**Comment by afilini** [comment]
I don't think there's much documentation unfortunately, I'll give you the steps here while we finish up the videos:

- Once you have the multisig created open it and tap on "View wallet config" from the main screen (below the balance)
- Tap on the dots at the top right
- Select "Export wallet configuration"
- Select "Portal"
- Follow the instructions on screen

On Portal you will be able to double check everything (multisig type, threshold, keys present, etc) and once confirmed at the end it will switch to the multisig and the addresses should match.

I'm gonna close this issue now, feel free to add more comments if you need anything else!

**Comment by alexandre-k** [comment]
Hello,

Thank you, it worked with these steps, I just tried it.
